{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60498388",
  "multipleFaultNumbers": null,
  "date": "2020-12-11T03:38:17",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-12-11T03:38:17",
  "information": "",
  "actualTimeOfRestoration": "2020-12-11T03:38:17",
  "outageCentrePoint": {
    "lat": 53.916704,
    "lng": -2.960225
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 0NP, FY6 0NR, FY6 0NS",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}